version: "3"

services:
  app:
    container_name: appbank
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"